
const express = require('express')
const router = express.Router()
const adminBeverageRouter = require('./adminBeverage')
const adminPermissionRouter = require('./adminPermission')
const adminAccountRouter = require('./adminAccount')
const adminSupplierRouter = require('./adminSupplier')
const adminCategoryrRouter = require('./adminCategory')
const adminReportRouter = require('./adminReport')
const adminUnitRouter = require('./adminUnit')
const adminIngredientRouter = require('./adminIngredient')
const adminPromotionRouter = require('./adminPromotion')
const adminBeverageIngredientRouter = require('./adminBeverageIngredient')
const adminCustomerRouter = require('./adminCustomer')
const adminOrderRouter = require('./adminOrder')
const adminVoucherRouter = require('./adminVoucher')

const adminController = require('../app/controllers/AdminController')

router.use('/voucher', adminVoucherRouter)
router.use('/order', adminOrderRouter)
router.use('/customer', adminCustomerRouter)
router.use('/beverageIngredient', adminBeverageIngredientRouter)
router.use('/report', adminReportRouter)
router.use('/category', adminCategoryrRouter)
router.use('/promotion', adminPromotionRouter)
router.use('/ingredient', adminIngredientRouter)
router.use('/unit', adminUnitRouter)
router.use('/supplier', adminSupplierRouter)
router.use('/account', adminAccountRouter)
router.use('/permission', adminPermissionRouter)
router.use('/beverage', adminBeverageRouter)
router.get('/', adminController.index)

module.exports = router
